template: hi template!

database:
  driverClass: org.mariadb.jdbc.Driver
  user: root
  password: cc
  url:
  properties:
    charSet: UTF-8

server:
  rootPath: '/api/*'
  applicationConnectors:
    - type: http
      port: 8080

logging:
  level: INFO
  loggers:
    net.skyee.AppService:
      level: info
      additive: false
      appenders:
        - type: file
          currentLogFilename: ./log/appService.log
          archivedLogFilenamePattern: ./log/appService-%d.log.gz
          archivedFileCount: 5
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
    - type: file
      threshold: ALL
      currentLogFilename: ./log/xdropwizard.log
      archivedLogFilenamePattern: ./log/xdropwizard-%d.log.gz,
      archivedFileCount: 5
      timeZone: UTC